---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: LaTeX-Importer
no_index:
  directory:
    - t
    - inc
requires:
  Config::AutoConf: '0.09'
  Digest::MD5: '0'
  File::Slurp: '0'
  Getopt::Std: '0'
  Memoize: '0'
  Test::More: '0'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
